# Generated by Django 4.0.5 on 2022-06-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sys_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('MOD_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('MOD_NOM', models.CharField(max_length=100, verbose_name='Nome')),
                ('MOD_ROT', models.CharField(max_length=100, verbose_name='Rota URL')),
                ('MOD_ORD', models.SmallIntegerField(null=True, verbose_name='Ordem')),
                ('MOD_STA', models.BooleanField(default=1, verbose_name='Status')),
                ('MEN_ID', models.ForeignKey(db_column='MEN_ID', on_delete=django.db.models.deletion.PROTECT, to='sys_menu.menu', verbose_name='Menu')),
            ],
            options={
                'db_table': 'MODULOS',
                'ordering': ['MOD_ORD'],
            },
        ),
    ]
