# Generated by Django 4.0.5 on 2022-06-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='MOD_MDL',
            field=models.CharField(default=1, max_length=100, verbose_name='Modulo'),
            preserve_default=False,
        ),
    ]
