# Generated by Django 4.0.5 on 2022-06-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0002_modulo_mod_mdl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='MOD_ROT',
        ),
    ]
