# Generated by Django 4.0.5 on 2022-06-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0003_remove_modulo_mod_rot'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='MOD_NUMPAG',
            field=models.SmallIntegerField(null=True, verbose_name='Paginas'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='MOD_MDL',
            field=models.CharField(choices=[('contenttype', 'contenttypes'), ('group', 'auth'), ('logentry', 'admin'), ('menu', 'sys_menu'), ('modulo', 'sys_modulo'), ('permissao', 'sys_permissao'), ('permission', 'auth'), ('session', 'sessions'), ('usuario', 'sys_usuario')], max_length=100, verbose_name='Modelo'),
        ),
    ]
