# Generated by Django 4.0.5 on 2022-06-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0005_alter_modulo_mod_numpag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='MOD_NUMPAG',
            field=models.SmallIntegerField(default=25, verbose_name='Paginas'),
        ),
    ]
