# Generated by Django 4.0.5 on 2022-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0006_alter_modulo_mod_numpag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='MOD_ORD',
            field=models.SmallIntegerField(default=1, verbose_name='Ordem'),
            preserve_default=False,
        ),
    ]
