# Generated by Django 4.0.5 on 2022-06-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0007_alter_modulo_mod_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='MOD_STAMEN',
            field=models.BooleanField(default=1, verbose_name='Status Menu'),
        ),
    ]
