# Generated by Django 4.0.5 on 2022-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0008_modulo_mod_stamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='MOD_STAMEN',
            field=models.SmallIntegerField(default=1, verbose_name='Status Menu'),
        ),
    ]
