# Generated by Django 4.0.5 on 2022-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0009_alter_modulo_mod_stamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='MOD_MDL',
            field=models.CharField(choices=[('contenttype', 'contenttype'), ('group', 'group'), ('logentry', 'logentry'), ('menu', 'menu'), ('modulo', 'modulo'), ('permissao', 'permissao'), ('permission', 'permission'), ('session', 'session'), ('usuario', 'usuario')], max_length=100, verbose_name='Modelo'),
        ),
    ]
