# Generated by Django 4.0.5 on 2022-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0012_modulo_mod_mdldnm'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='MOD_NOMPAG',
            field=models.CharField(default=1, max_length=100, verbose_name='Título Página'),
            preserve_default=False,
        ),
    ]
