# Generated by Django 4.0.5 on 2022-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0013_modulo_mod_nompag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='MOD_MDLDNM',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Dinâmico'),
        ),
    ]
