# Generated by Django 4.0.5 on 2022-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0014_alter_modulo_mod_mdldnm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='MOD_MDL',
            field=models.CharField(choices=[('dashbordatendimento', 'dashbordatendimento'), ('group', 'group'), ('menu', 'menu'), ('modulo', 'modulo'), ('permission', 'permission'), ('session', 'session'), ('usuario', 'usuario')], max_length=100, verbose_name='Modelo'),
        ),
    ]
