# Generated by Django 4.0.5 on 2022-07-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_modulo', '0015_alter_modulo_mod_mdl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='MOD_MDL',
            field=models.CharField(choices=[('acessos', 'acessos'), ('dashbordatendimento', 'dashbordatendimento'), ('group', 'group'), ('menu', 'menu'), ('modulo', 'modulo'), ('permission', 'permission'), ('session', 'session'), ('usuario', 'usuario')], max_length=100, verbose_name='Modelo'),
        ),
    ]
