# Generated by Django 4.0.5 on 2022-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('ACE_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('ACE_URL', models.CharField(max_length=150, verbose_name='URL')),
                ('id_usuario', models.IntegerField(verbose_name='Usuário')),
                ('ACE_DATHOR', models.DateTimeField(verbose_name='Data e Hora')),
                ('ACE_PST', models.TextField(verbose_name='Post')),
                ('ACE_IP', models.CharField(max_length=20, verbose_name='IP')),
            ],
            options={
                'db_table': 'ACESSO_PAGINAS',
            },
        ),
    ]
