# Generated by Django 4.0.5 on 2022-07-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_acessos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessos',
            old_name='id_usuario',
            new_name='ID_USU',
        ),
    ]
