# Generated by Django 4.0.5 on 2022-07-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_acessos', '0005_alter_acessos_ace_dathor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessos',
            name='ACE_DATHOR',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora'),
        ),
    ]
