# Generated by Django 4.0.5 on 2022-06-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MEN_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('MEN_NOM', models.CharField(max_length=100, verbose_name='Nome')),
                ('MEN_ORD', models.SmallIntegerField(null=True, verbose_name='Ordem')),
                ('MEN_STA', models.BooleanField(default=1, verbose_name='Status')),
            ],
            options={
                'db_table': 'MENU',
                'ordering': ['MEN_ORD'],
            },
        ),
    ]
