# Generated by Django 4.0.5 on 2022-06-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIOS',
        ),
    ]
