# Generated by Django 4.0.5 on 2022-06-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_permissao', '0001_initial'),
        ('sys_usuario', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='PER_ID',
            field=models.ForeignKey(db_column='PER_ID', default=1, on_delete=django.db.models.deletion.PROTECT, to='sys_permissao.permissao', verbose_name='Menu'),
            preserve_default=False,
        ),
    ]
