# Generated by Django 4.0.5 on 2022-06-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_permissao', '0001_initial'),
        ('sys_usuario', '0004_alter_usuario_per_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='PER_ID',
            field=models.ForeignKey(db_column='PER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_permissao.permissao'),
        ),
    ]
