# Generated by Django 4.0.5 on 2022-06-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_usuario', '0005_alter_usuario_per_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='PER_ID',
        ),
    ]
